[package]
name = "rust-hello"
version = "1.0.0"
description = "Hello World program written in Rust"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-hello"
path = "hello.rs"
