haskell_binary(
    name = "haskell-hello",
    srcs = ["Main.hs"],
    compiler_flags = [
        "-Wall",
        "-O",
        "-g",
    ],
    linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "main",
    actual = ":haskell-hello",
)
