name: dart_fibonacci
description: Fibonacci program written in Dart
version: 1.0.0
repository: https://github.com/altersabeh/fibonacci

environment:
  sdk: ^3.1.5

executables:
  dart-fibonacci: dart_fibonacci

dependencies:
  path: ^1.8.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
