name:                codes
version:             1.0.0.0
github:              "altersabeh/codes"
license:             MIT
author:              "altersabeh"
maintainer:          "betamaximum22@gmail.com"
copyright:           "2023 altersabeh"

extra-source-files:
- README.md
- LICENSE

synopsis:            Repository for My Codes
category:            Others

description:         Please see the README on GitHub at <https://github.com/altersabeh/codes#README.md>

language: GHC2021

dependencies:
  - base >= 4.18 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  haskell-hello:
    main:                main.hs
    source-dirs:         haskell/hello
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
