name:                codes
version:             1.0.0.0
github:              "altersabeh/codes"
license:             MIT
author:              "altersabeh"
maintainer:          "betamaximum22@gmail.com"
copyright:           "2023 altersabeh"

extra-source-files:
- README.md
- LICENSE

synopsis:            Repository for My Codes
category:            Others

description:         Please see the README on GitHub at <https://github.com/altersabeh/codes#README.md>

language: GHC2021

dependencies:
  - base >= 4.18 && < 5
  - time >= 1.12 && < 2
  - unix >= 2.8 && < 3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  haskell-hello:
    main:                hello.hs
    source-dirs:         haskell/hello

  haskell-fibonacci:
    main:                fibonacci.hs
    source-dirs:         haskell/fibonacci
