[tool.poetry]
name = "codes"
version = "1.0.0"
description = "Repository for My Codes"
authors = ["altersabeh <betamaximum22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
python-hello = "python.hello.main:main"
python-greeter = "python.greeter.main:main"
python-fibonacci = "python.fibonacci.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
