cxx_binary(
    name = "c-fibonacci",
    srcs = ["src/fibonacci.c"],
    compiler_flags = [
        "-Wall",
        "-O2",
        "-g",
    ],
    linker_flags = [
        "-lgmp",
    ],
    visibility = ["PUBLIC"],
)

alias(
    name = "main",
    actual = ":c-fibonacci",
)
