cxx_binary(
    name = "c++-random",
    srcs = ["src/randomNumberGame.cpp"],
    compiler_flags = [
        "-Wall",
        "-O2",
        "-g",
    ],
    linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
  name = "main",
  actual = ":c++-random",
)
