cxx_binary(
  name = "c-hello",
  srcs = ["src/hello.c"],
  compiler_flags = [
    "-Wall",
    "-O2",
    "-g",
  ],
  linker_flags = [],
  visibility = ["PUBLIC"],
)

alias(
  name = "main",
  actual = ":c-hello",
)
