name: dart_greeter
version: 1.0.0
description: Greeter program written in Dart
repository: https://github.com/altersabeh/codes
homepage: https://github.com/altersabeh/codes#README

topics:
  - command-line-utilities

environment:
  sdk: ^3.1.5

executables:
  dart-greeter: dart_greeter

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
