cxx_binary(
    name = "c-greeter",
    srcs = ["src/greeter.c"],
    compiler_flags = [
        "-Wall",
        "-O2",
        "-g",
    ],
    linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "main",
    actual = ":c-greeter",
)
