rust_binary(
    name = "rust-greeter",
    srcs = ["src/greeter.rs"],
    rustc_flags = [
        "-O",
        "-g",
    ],
    crate_root = "src/greeter.rs",
    visibility = ["PUBLIC"],
)

alias(
    name = "main",
    actual = ":rust-greeter",
)
