rust_binary(
    name = "rust-fibonacci",
    srcs = ["src/fibonacci.rs"],
    rustc_flags = [
        "-O",
        "-g",
    ],
    crate_root = "src/fibonacci.rs",
    visibility = ["PUBLIC"],
)

alias(
    name = "main",
    actual = ":rust-fibonacci",
)
